export const LLEGADA_CLIENTE = 'LLEGADA_CLIENTE';
export const SALIDA_CLIENTE = 'SALIDA_CLIENTE';
export const INIICIO_ATENCION_CLIENTE = 'INIICIO_ATENCION_CLIENTE';
export const FIN_ATENCION_CLIENTE = 'FIN_ATENCION_CLIENTE';
export const INIICIO_SIMULACION = 'INIICIO_SIMULACION';
export const FIN_SIMULACION = 'FIN_SIMULACION';
