export const REPARADOR_OCUPADO = 'OCUPADO';
export const REPARADOR_LIBRE = 'LIBRE';
export const CLIENTE_SIENDO_ATENDIDO = 'CLIENTE_SIENDO_ATENDIDO';
export const CLIENTE_FINALIZADO = 'CLIENTE_FINALIZADO';
export const CLIENTE_PENDIENTE = 'CLIENTE_PENDIENTE';
export const REPARACION_PAGADA = 'REPARACION_PAGADA'
export const REPARACION_GRATIS = 'REPARACION_GRATIS'
